# Generated by Django 2.1.15 on 2020-07-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_confirmed', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('newly_confirmed', models.IntegerField()),
                ('newly_recovered', models.IntegerField()),
                ('newly_deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('cases', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Covid_cases.Cases')),
            ],
        ),
    ]
